USE [ZSINO]
GO

/****** Object:  Table [dbo].[SINOX001_Catalogo_Tipo]    Script Date: 12/28/2018 09:34:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SINOX001_Catalogo_Tipo](
	[SINOX001_Id] [int] NOT NULL,
	[SINOX001_Hidrocarburo] [varchar](100) NOT NULL,
	[SINOX001_Proceso] [varchar](100) NOT NULL,
	[SINOX001_Tipo] [varchar](100) NULL,
	[SINOX001_UDM] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SINOX001_Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

