USE [ZSINO]
GO

/****** Object:  Table [dbo].[SINOX009_Trimestres]    Script Date: 12/28/2018 09:35:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SINOX009_Trimestres](
	[SINOX001_Mes] [int] NOT NULL,
	[SINOX001_Trimestre] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SINOX001_Mes] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

