USE [ZSINO]
GO

/****** Object:  Table [dbo].[SINOX003_Catalogo_UDM]    Script Date: 12/28/2018 09:35:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING OFF
GO

CREATE TABLE [dbo].[SINOX003_Catalogo_UDM](
	[SINOX003_Id] [int] NOT NULL,
	[SINOX003_UDM] [varchar](10) NOT NULL,
	[SINOX003_Descripcion] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SINOX003_Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

