USE [ZSINO]
GO

/****** Object:  Table [dbo].[SINOX002_Catalogo_Region]    Script Date: 12/28/2018 09:35:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING OFF
GO

CREATE TABLE [dbo].[SINOX002_Catalogo_Region](
	[SINOX002_Id] [int] NOT NULL,
	[SINOX002_Region] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SINOX002_Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

